name: Deploy ke VM Instance GCP

on:
  push:
    branches:
      - main 

# jobs:
#   deploy:


#     steps:
#       - name: Checkout kode
#         uses: actions/checkout@v2

#       - name: Deploy ke Instance VM GCP
#         id: deploy-vm
#         uses: google-github-actions/ssh-compute@v0
#         with:
#           instance_name: 'cicd' # Ganti dengan nama instance Anda
#           zone: 'asia-southeast2-a' # Ganti dengan zona instance Anda
#           ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY_SERVER_DEV }}
#           command: 'cd /home/adi_kannatasik/gitcicd && git pull origin main && npm install && node index.js' # Sesuaikan dengan perintah yang sesuai
jobs:
  job_id:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - id: 'compute-ssh'
      uses: 'google-github-actions/ssh-compute@v0'
      with:
        instance_name: 'cicd'
        zone: 'asia-southeast2-a'
        ssh_private_key: '${{ secrets.SSH_PRIVATE_KEY_SERVER_DEV }}'
        command: 'echo Hello world'
