name: Deploy to GCP

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ success() && (github.ref == 'refs/heads/main') }}
    concurrency:
      group: ci-${{ github.ref }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      # - name: Build application
      #   run: npm run build # Adjust this script according to your app

      # - name: Authenticate with GCP
      #   uses: google-github-actions/auth@v0.5
      #   with:
      #     credentials: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Deploy to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY_SERVER_DEV }}
          port: 22
          script: |
            cd /home/adi_kannatasik/gitcicd
            git pull origin main
            git status
            node -v
            node index.js
